-- Attack angles — the opening argument for each city.
--
-- Every city needs an answer to "why would THIS council care?", and that
-- answer is different depending on what is already true there. A volunteer
-- opening a city page should not have to work it out from scratch.
--
-- TWO KINDS OF ANGLE, DELIBERATELY SEPARATED:
--
--   attack_angle        derived from data we hold, and recomputable. Set by
--                       this migration and safe to regenerate.
--   attack_angle_notes  written by a human for that specific city. Never
--                       touched by any script.
--
-- If those shared one column, the next regeneration would silently destroy
-- researched work — which is the same class of mistake as stamping
-- code_reviewed_at on a city nobody read.

begin;

alter table cities add column if not exists attack_angle text;
alter table cities add column if not exists attack_angle_notes text;

comment on column cities.attack_angle is
  'Derived opening argument. Regenerated by 0010 — do not hand-edit.';
comment on column cities.attack_angle_notes is
  'Human-written, city-specific strategy. Never written by a script.';

-- ---------------------------------------------------------------------------
-- Derivation, weakest signal first so stronger ones overwrite.
-- ---------------------------------------------------------------------------

-- 1. Baseline: nothing distinctive known yet. Honest rather than blank.
update cities set attack_angle =
  'No specific hook identified yet. Start with the standard case: shielded '
  || 'fixtures cut the utility bill while lighting the ground better, and the '
  || 'model ordinance is drafted and free to adopt.';

-- 2. In a priority county — the coalition is already working the area, so a
--    city here inherits momentum and contacts.
update cities c set attack_angle =
  'Priority county — the coalition is already active nearby, so this council '
  || 'can be approached alongside neighbors rather than cold. Lead with what '
  || 'comparable cities in the county have already done.'
from counties co
where co.id = c.county_id and co.priority >= 4;

-- 3. The county itself has an ordinance, but a county ordinance reaches only
--    unincorporated land — so the city is a literal hole in the map. This is
--    the single most concrete ask available.
update cities c set attack_angle =
  'The county has already adopted an ordinance, but a California county '
  || 'ordinance covers only unincorporated land — so it stops at this city '
  || 'limit. The ask is narrow and provable: adopt the standard the county '
  || 'already accepted, so the protection does not end at the sign.'
from counties co
where co.id = c.county_id
  and co.ordinance_title is not null
  and c.status <> 'passed';

-- 4. Shares a county with a certified dark sky place. The strongest emotional
--    and economic argument in the set: the asset already exists and this
--    city's sky glow is what degrades it.
update cities c set attack_angle =
  'This county contains a certified International Dark Sky Place. That is an '
  || 'existing local asset with real visitor value, and sky glow from '
  || 'surrounding cities is what erodes it. Argue protection of something the '
  || 'county already has, not adoption of something new.'
from dark_sky_places d
where d.county_id = c.county_id and c.status <> 'passed';

-- 5. Already passed. The angle is no longer adoption — it is depth.
update cities set attack_angle =
  'Ordinance already adopted. The work here is strengthening, not passing: '
  || 'check for a color temperature cap, an amortization schedule for existing '
  || 'fixtures, and whether enforcement is actually funded. An ordinance that '
  || 'only binds new construction changes very little in a built-out city.'
where status = 'passed';

commit;

select
  count(*) filter (where attack_angle is not null) as with_angle,
  count(*)                                          as total
from cities;
